stages:
- test
- analyze
- build

########
# Test #
########
.test: &test
  stage: test
  tags: [amd64]
  before_script:
  - apt-get update -qq
  - apt-get install --no-install-recommends -y python3 python3-pytest python3-sqlalchemy python3-setproctitle python3-setuptools python3-yaml python3-zmq
  script:
  - py.test-3 -v --junitxml=reactobus.xml tests
  artifacts:
    reports:
      junit:
      - reactobus.xml

test-debian-9:
  <<: *test
  image: debian:9
test-debian-10:
  <<: *test
  image: debian:buster
test-ubuntu-18.04:
  <<: *test
  image: ubuntu:18.04
test-ubuntu-18.10:
  <<: *test
  image: ubuntu:18.10
test-ubuntu-19.04:
  <<: *test
  image: ubuntu:19.04

###########
# Analyze #
###########
black:
  stage: analyze
  image: debian:buster
  tags: [amd64]
  before_script:
  - apt-get update -qq
  - apt-get install --no-install-recommends -y python3-pip python3-setuptools
  - pip3 install black
  script:
  - LC_ALL=C.UTF-8 LANG=C.UTF-8 black --check .

# static analysis with bandit
include:
  template: SAST.gitlab-ci.yml
sast:
  tags: [amd64-dind]
  stage: analyze
  variables:
    DOCKER_DRIVER: overlay2
    SAST_DEFAULT_ANALYZERS: "bandit"

#########
# Build #
#########
docker:
  image: docker:stable
  tags: [amd64-dind]
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  script:
  - docker build .
