stages:
- test

########
# Test #
########
.test: &test
  stage: test
  tags: [amd64]
  before_script:
  - apt-get update -qq
  - apt-get install --no-install-recommends -y python3 python3-pytest python3-sqlalchemy python3-setproctitle python3-setuptools python3-yaml python3-zmq
  script:
  - py.test-3 -v --junitxml=reactobus.xml tests
  artifacts:
    reports:
      junit:
      - reactobus.xml

test-debian-9:
  <<: *test
  image: debian:9
test-debian-10:
  <<: *test
  image: debian:buster
test-ubuntu-18.04:
  <<: *test
  image: ubuntu:18.04
test-ubuntu-18.10:
  <<: *test
  image: ubuntu:18.10
test-ubuntu-19.04:
  <<: *test
  image: ubuntu:19.04

