language: python
python:
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "3.6-dev"

install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pip install coveralls

script:
    - py.test tests -v --cov=ReactOBus

after_success:
    coveralls
